# Page settings
baseurl = "localhost:1313"
title = "PHYTAGO - Aus Pflanzen pflanzen Pflanzen - Delikatessen aus ökologischer Kreislaufproduktion"
languageCode = "en-us"
theme = "hugo-elate-theme"
video = "video-chia.mp4"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "**P H Y T A G O**"
    intro = "Produkte"
    services = "Besonderheiten"
    counters = "Philosophie"
    testimonials = "Über uns"
    contact = "Kontakt"
    account = "Kundenbereich"
    work = "Jungpflanzen"
    workb = "Gourmetpilze"
    about = "Philosophie"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
  # [[menu.postpend]]
    #  url = "#fh5co-work"
      #name = "Produkte"
      #weight = 9

    # postpended links
    # [[menu.postpend]]
    #   url = "#fh5co-counters"
    #   name = "Philosophie"
    #   weight = 11

    [[menu.postpend]]
      url = "/verwaltung/kundenbereich"
      name = "Kundenbereich"
      weight = 12


  # Hero section
  [params.hero]
  #  title = "Individualisierter Anbau"
    subtitle1 = "maximale Fri­sche"
    subtitle2 = "höchste Qualität"
    subtitle3 = "Ressourcenschonung"
    subtitle4 = "ganzjährig konstante Liefe­rung"
    subtitle5 = "Individualisierter Anbau"
    video = "video-chia.mp4"

  # Intro section
  # Available icons: https://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Jungpflanzen"
    description = "Unsere Jungpflanen tragen in die geballte Energie in sich, die die Pflanze benötigt, um groß zu werden. Der Anteil an Vitaminen, Spurenelementen (besonders Vitamin A, B6, C und Eisen) sowie Proteinen ist daher in den kleinen Pflänzchen um ein Vielfaches höher als in der gleichen Menge des ausgewachsenen Gemüses. "
    url = "/produkte/jungpflanzen"
    button = "Jungpflanzen"
    icon = "icon-plant"
    img = "Microgreens.jpg"

  [[params.intro.item]]
    title = "Gourmetpilze"
    description = "Unsere Speisepilze genießen in der Welt generell ein hohes Ansehen und leisten einen wichtigen Beitrag für die gesunde Ernährung. Sie schmecken nicht nur herrvoragend, sondern liefern dem Körper neben Eiweißen, auch wichtige Vitamine und Spurenelemente. (Vitamin A, B2, B5, D, Eisen, Zink und Selen) Sie sind echte Multitalente."
    url = "/produkte/gourmetpilze"
    button = "Gourmetpilze"
    icon = "icon-diamond"
    img = "Pilze.jpg"

  [[params.intro.item]]
    title = "Vitalpulver"
    description = "Vitalstoffe sind überwiegend als Biokatalysatoren in Zellen und Geweben bei Anwesenheit von Wasser, Sauerstoff und Kohlensäure (letztere bei Pflanzen) wirksame lebenswichtige Bestandteile. Dazu gehören nach bisherigen Feststellungen: Enzyme, Co-Enzyme, Vitamine, Hormone, exogen-essentielle Aminosäuren, exogen-essentielle Fettsäuren, Haupt- und Spurenelemente, Duft- und Geschmacksstoffe."
    url = "/produkte/vitalstoffe"
    button = "Vitalstoffe"
    icon = "icon-diamond"
    img = "Gewuerze.jpg"

  #  [[params.intro.item]]
  #    title = "Individueller Anbau"
  #    description = "Gewürze sind kulinarisch von sehr hoher Bedeutung. Mit Gewürzen verfeinern wir nicht nur unsere Mahlzeiten, sondern können Entzündungen hemmen, Krankheiten bekämpfen und die Verdauung fördern. Das geht komplett, anders als bei Medikamenten, ohne Nebenwirkungen. Auch wirken sie antiviral, antibakteriell und pilzbekämpfend."
  #    url = "/ind-anb.md"
  #    button = "Zur Produktpalette"
  #    icon = "icon-home"
  #    img = "Gewuerze.jpg"

  # [params.intro.video]
  #   enable = true
  #   title = "Sieh dir das Video an!"
  #   icon = "icon-play2"
  #   url = "http://localhost:1313"

# Work section
   [params.work]
    enable = false
    title = ""
    description = ""
    footertext = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = ""

    [[params.work.row]]
      img = ""
      alt = ""
      title = ""
      subtitle = " "


  # ----------------------------PRODUKTPALETTE GOURMETPILZE
  [params.workb]
   enable = false
   title = " "
   description = ""
   footertext = ''

   [[params.workb.row]]
     img = ""
     alt = ""
     title = ""
     subtitle = ""
#Beschreibung:
#Hierzulande ist der Rosenseitling wegen seiner einzigartigen Farbe und Geschmacks ein beliebt.
#Die den Blättrigen aufbau sieht er auch durch seine schöne Farbe wie eine Rose aus.
#Tipp:
#sehr fleischig, "fleischersatz"
#Valentintag-für Koch*in: ein kleines Töpfchn mit angezüchteten Rosenseitlingen,

   [[params.workb.row]]
     img = ""
     alt = ""
     title =  ""
     subtitle = ""
#Beschreibung:
#Er ist kräftig intensiv und den Geschmack haben sie noch eine halbe Stunde danach im Mund
#Tipp:
#für kurzgebratene Sachen oder Schmoren geeignet.
#Shiitake mögen Thymian, Rosmarin und Petersilie.

   [[params.workb.row]]
     img = "ENOKI.jpg"
     alt = "Image3"
     title = "Enoki -  Die kleine Flamme des Lebens"
     subtitle =  ""
     # Verbesserung der Verträglichkeit von Chemo- und Strahlentherapie
     # Die immunmodulierenden Eigenschaften des Enoki stärken einen Organismus, der aufgrund einer schulmedizinischen Tumortherapie besonders belastet wird. Sowohl eine verbesserte Verträglichkeit der Therapie als auch ein Schutz vor weiteren Zellveränderungen kann durch die antioxidativ wirkenden Inhaltsstoffe erreicht werden.
     # • Immunmodulation bei Allergien und Infektionen
     # Der Enoki stimuliert unter anderem die Interferon-Gamma-Produktion, die bei der Immunantwort des Organismus von großer Bedeutung ist. Bemerkenswert ist der modulierende Effekt auf das Immunsystem. Deshalb kann der Enoki zum Schutz vor Infektionen ebenso wie bei überschießenden Abwehrreaktionen (zum Beispiel Allergien) eingesetzt werden.
     # • Chronisches Müdigkeitssyndrom
     # Als vitalisierender Pilz mit hohem Gehalt an Polysacchariden kann der Enoki auch bei chronischem Müdigkeitssyndrom, wie es unter anderem als Begleiterscheinung anderer Erkrankungen auftritt, eingesetzt werden.


  [params.testimonials]
    enable = true
    title = "Das TEAM"
   # description = "Portfolios unserer Gourmetpilze"
    description = "Unsere kompetenten Kontaktpersonen"


    [[params.testimonials.item]]
      quote = "Der Macher - Wahrscheinlich unsere stärkste Treibende Kraft, mit hohem betriebswirtschaftlichem Potential. Sein stetig wachsendes Wissen in den Metiers der Wirtschaft, Kundenorientierung und Struktur, ist er auch für fachfremde eine Quelle für Information und Motivation. Der richtige Geschäftsmann."
      person = 'Nico'
      img = "person1.png"
      alt = "bild"

    [[params.testimonials.item]]
      quote = "Der grüne Daumen - Die Frau mit dem Kopf hinter den pflanzlichen Fragen. Ihre Hingabe für alle biologisch, chemischen Zusammenhänge erkennt man natürlich an der Qualität unserer Produkte. Mit fundiertem Wissen wird es immer neue Methoden und Produkte bei uns geben."
      person = 'Celiné'
      img = "person2.png"
      alt = "bild"

    [[params.testimonials.item]]
      quote = "Der Techniker - Alles rund ums Thema Hardware und Infrastruktur wird von unserem Techniker übernommen. Mit größter Sorgfalt wird bei uns ausgewählt. Er legt nicht nur Wert auf Funktion sondern auch darauf, dass Teile mit guter Ökobilanz und angemessenem Energieverbrauch verbaut werden."
      person = 'Robert'
      img = "person3.png"
      alt = "bild"


  # Services section
  [params.services]
    enable = true
    title = "Besonderheiten der Produktion"
    description = "Der Workflow des Herstellungsprozesses ist nicht nur für den Menschen optimiert, sondern auch nachhaltig und umweltbewusst konzipiert. Ganz prima mit dem Streben nach ZeroWaste."

    [[params.services.item]]
      title = "Individualisierte, bedarfsorientierte Versorgung"
      description = "Hier ist Platz für eine Grafik, und eine Beschreibung."
      icon = "icon-money"


    [[params.services.item]]
      title = "RST - Ressource-Saving-Tool "
      description = "Hier ist Platz für eine Grafik, und eine Beschreibung."
      icon = "icon-chart"
      # puzzle

    # [[params.services.item]]
    #  title = "Web &amp; Interface"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #  icon = "icon-layers2"

    #[[params.services.item]]
    #  title = "Photo &amp; Video"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #  icon = "icon-video2"

  # About section
  [params.about]
    enable = true
    title = "Kurzfilm - PHYTAGO"
    description = "In diesem Kurzfilm legen wir unsere Arbeitsweise dar, erklären Euch warum wir das machen und wie wir überhaupt dazukamen."

    [params.about.video]
      enable = true
      # title = "Sieh dir das Video an!"
      icon = "icon-play2"
      url = "https://www.youtube.com/watch?v=mCSrPOwjzr0"


    #[[params.about.item]]
    #  name = "Optimierung"
    #  position = "100 % Geschmack"
    #  description = "97% kürzere Transportwege   95% weniger Wasserverbrauch   90% weniger Dünger"
    #  img = "person2.jpg"
    #  alt = "philosophy1"
     # social = [
     #   ["icon-twitter", "#"],
     #   ["icon-facebook", "#"],
     #   ["icon-github", "#"]
     # ]

    #[[params.about.item]]
    #  name = "Nachhaltigkeit"
    #  position = "  0% Pestizide"
    #  description = "0% Abfall           0% chemischer Dünger                 0% Ausfall"
    #  img = "person3.jpg"
    #  alt = "philosophy1"
    #  social = [
    #    ["icon-twitter", "#"],
    #    ["icon-facebook", "#"],
    #    ["icon-dribbble", "#"]
    #  ]

  # Counters section
  [params.counters]
    enable = true
    title = "Philosophie"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Geschmack"
      icon = "icon-heart"
      from = 0
      to = 100
      interval = 1
      speed = 200

   [[params.counters.item]]
      description = "Kürzerer Transport"
      icon = "icon-plane"
      from = 0
      to = 97
      interval = 1
      speed = 200

    [[params.counters.item]]
       description = "Weniger Wasser"
       icon = "icon-drop"
       from = 0
       to = 90
       interval = 1
       speed = 200

     [[params.counters.item]]
        description = "Weniger Dünger"
        icon = "icon-wrench"
        from = 0
        to = 90
        interval = 1
        speed = 200

      [[params.counters.item]]
        description = "Pestizide"
        icon = "icon-close"
        from = 100
        to = 0
        interval = 1
        speed = 200

     [[params.counters.item]]
        description = "Abfall"
        icon = "icon-trash"
        from = 100
        to = 0
        interval = 1
        speed = 200

      [[params.counters.item]]
         description = "Chemischer Dünger"
         icon = "icon-chemistry"
         from = 100
         to = 0
         interval = 1
         speed = 200

       [[params.counters.item]]
          description = "Ausfall"
          icon = "icon-loop"
          from = 100
          to = 0
          interval = 1
          speed = 200

  #  [[params.counters.item]]
  #    description = "Cups of coffee"
  #    icon = "icon-cup"
  #    from = 0
  #    to = 1302
  #    interval = 50
  #    speed = 5000

  #  [[params.counters.item]]
  #    description = "Happy clients"
  #    icon = "icon-people"
  #    from = 0
  #    to = 52
  #    interval = 50
  #    speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Verbinden ist Zukunft"
    description = "In einem Zeitalter der unbegrenzten Möglichkeiten wird es immer Verbesserungsmöglichkeiten geben. Wir freuen uns auf Anregungen."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-linkedin", "linkedIn.link.go"],
        ["icon-facebook", "facebook.link.go"],
        ["icon-twitter", "twitter.link.go"],
        ["icon-globe", "Persönliche Internetpräsenz"]
      ]

    name = "Ihr Name"
    email = "Ihre Email"
    phone = "Ihre Telefonnummer"
    message = "Ihre Nachricht"
    button = "Nachricht senden"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; PHYTAGO, All Rights Reserved. '
    links = [
        ["icon-lock", "/verwaltung/datenschutz"],
        ["icon-paperclip", "/verwaltung/agb"],
        ["icon-people", "/verwaltung/impressum"]
      ]
